### ISSUE TITLE
Bug prenotazioni

### ISSUE THREAD

**Issue by rastafaninplakeibol** [Confidential-Storm-Project/ConfidentialStormServer#4]
Trovato bug nelle prenotazioni:
Se durante una prenotazione attiva (non ancora confermata o annullata) un utente fa il logout, il client perde ogni informazione riguardo la prenotazione, però nonostante tutto sul server dovrebbe risultare che l'utente è ancora in prenotazione ed impedirti di prenotare altri posti, cosa che però non succede e ho comunque la possibilità di prenotare, confermare e annullare nuovi parcheggi

**Comment by nicholas0g** [comment]
Errore risolto, era causato da una problematica di controllo su uno dei campi del database
