### ISSUE TITLE
Problema invio response errato

### ISSUE THREAD

**Issue by Thecave3** [Confidential-Storm-Project/ConfidentialStormServer#5]
Per quanto sono sicuro che ci sia un problema nell'app android, sospetto che vi siano errori anche nel server. Non credo che questa qui sia la risposta che in caso di errore il server dovrebbe inviare.
  ```
07-04 18:54:42.562 20499-21041/storm.confidential.parknetwork I/PROFILE_FRAGMENT: <!DOCTYPE html><html><head><meta charset="utf-8">        <link rel="icon" type="image/png" href="assets/img/favicon.ico">        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">        <title>LaLaPArk Admin</title>        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">        <meta name="viewport" content="width=device-width"><!-- Bootstrap core CSS--><link href="/assets/css/bootstrap.min.css" rel="stylesheet"><!-- Animation library for notifications--><link href="/assets/css/animate.min.css" rel="stylesheet"><!-- Light Bootstrap Table core CSS--><link href="/assets/css/light-bootstrap-dashboard.css" rel="stylesheet"><link href="/assets/css/demo.css" rel="stylesheet"><!-- Fonts and icons--><link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">        <link href="http://fonts.googleapis.com/css?family=Roboto:400,700,300" rel="stylesheet" type="text/css">        <link href="/assets/css/pe-icon-7-stroke.css" rel="stylesheet"></head>    <body><div class="wrapper"><div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg"><div class="sidebar-wrapper"><div class="logo"><a class="simple-text" href="#">LALAPARK</a></div>                <ul class="nav"><li><a href="/admin/dash"><i class="pe-7s-graph"></i>                            <p>Dashboard</p></a></li>                    <li><a href="/admin/utenti"><i class="pe-7s-note2"></i>                            <p>Elenco Utenti</p></a></li>                    <li><a href="/admin/parcheggi"><i class="pe-7s-note2"></i>                            <p>Elenco Parcheggi</p></a></li>                    <li><a href="/admin/map"><i class="pe-7s-map-marker"></i>                            <p>Mappa</p></a></li>                    <li><a href="/admin/notifiche"><i class="pe-7s-bell"></i>                            <p>Invia comunicazione</p></a></li></ul></div></div>        <div class="main-panel"><nav class="navbar navbar-default navbar-fixed"><div class="container-fluid"><div class="navbar-header"><button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navigation-example-2"><span class="sr-only">Toggle navigation</span>                            <span class="icon-bar"></span>                            <span class="icon-bar"></span>                            <span class="icon-bar"></span></button>                        <a class="navbar-brand" href="#">Dashboard</a></div>                    <div class="collapse navbar-collapse"><ul class="nav navbar-nav navbar-right"><li><a href="/admin/logout"><p>Log out</p></a></li>                            <li class="separator hidden-lg hidden-md"></li></ul></div></div></nav>            <h1>Unexpected field</h1><h2></h2><pre>
Error: Unexpected field
                                                                                      at makeError (/root/ConfidentialStormServer/node_modules/multer/lib/make-error.js:12:13)
                                                                                      at wrappedFileFilter (/root/ConfidentialStormServer/node_modules/multer/index.js:40:19)
                                                                                      at Busboy.&lt;anonymous&gt; (/root/ConfidentialStormServer/node_modules/multer/lib/make-middleware.js:114:7)
                                                                                      at emitMany (events.js:108:13)
                                                                                      at Busboy.emit (events.js:182:7)
                                                                                      at Busboy.emit (/root/ConfidentialStormServer/node_modules/busboy/lib/main.js:38:33)
                                                                                      at PartStream.&lt;anonymous&gt; (/root/ConfidentialStormServer/node_modules/busboy/lib/types/multipart.js:213:13)
                                                                                      at emitOne (events.js:77:13)
                                                                                      at PartStream.emit (events.js:169:7)
                                                                                      at HeaderParser.&lt;anonymous&gt; (/root/ConfidentialStormServer/node_modules/dicer/lib/Dicer.js:51:16)</pre><footer class="footer"><div class="container-fluid"><p class="copyright pull-right">&copy; <script>document.write(new Date().getFullYear())</script> <a href="https://lalapark.it">LALAPARK</a>, fatto con amore da Nicholas che non ha altro di meglio da fare</p></div></footer></div></div></body><!-- Core JS Files--><script src="/assets/js/jquery-1.10.2.js" type="text/javascript"></script>        <script src="/assets/js/bootstrap.min.js" type="text/javascript"><
````

Se si nota bene dalla stacktrace il server come risposta invia una pagine HTML che mi sembra sia quella di amministrazione.

`<!DOCTYPE html><html><head><meta charset="utf-8">        <link rel="icon" type="image/png" href="assets/img/favicon.ico">        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">        <title>LaLaPArk Admin</title>        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">        <meta name="viewport" content="width=device-width"><!-- Bootstrap core CSS--><link href="/assets/css/bootstrap.min.css" rel="stylesheet"><!-- Animation library for notifications--><link href="/assets/css/animate.min.css" rel="stylesheet"><!-- Light Bootstrap Table core CSS--><link href="/assets/css/light-bootstrap-dashboard.css" rel="stylesheet"><link href="/assets/css/demo.css" rel="stylesheet"><!-- Fonts and icons--><link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">        <link href="http://fonts.googleapis.com/css?family=Roboto:400,700,300" rel="stylesheet" type="text/css">        <link href="/assets/css/pe-icon-7-stroke.css" rel="stylesheet"></head>    <body><div class="wrapper"><div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg"><div class="sidebar-wrapper"><div class="logo"><a class="simple-text" href="#">LALAPARK</a></div>                <ul class="nav"><li><a href="/admin/dash"><i class="pe-7s-graph"></i>                            <p>Dashboard</p></a></li>                    <li><a href="/admin/utenti"><i class="pe-7s-note2"></i>                            <p>Elenco Utenti</p></a></li>                    <li><a href="/admin/parcheggi"><i class="pe-7s-note2"></i>                            <p>Elenco Parcheggi</p></a></li>                    <li><a href="/admin/map"><i class="pe-7s-map-marker"></i>                            <p>Mappa</p></a></li>                    <li><a href="/admin/notifiche"><i class="pe-7s-bell"></i>                            <p>Invia comunicazione</p></a></li></ul></div></div>        <div class="main-panel"><nav class="navbar navbar-default navbar-fixed"><div class="container-fluid"><div class="navbar-header"><button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navigation-example-2"><span class="sr-only">Toggle navigation</span>                            <span class="icon-bar"></span>                            <span class="icon-bar"></span>                            <span class="icon-bar"></span></button>                        <a class="navbar-brand" href="#">Dashboard</a></div>                    <div class="collapse navbar-collapse"><ul class="nav navbar-nav navbar-right"><li><a href="/admin/logout"><p>Log out</p></a></li>                            <li class="separator hidden-lg hidden-md"></li></ul></div></div></nav>            <h1>Unexpected field</h1><h2></h2><pre>`

Si può avere il log della chiamata che ho fatto di upload? ( O comunque di una call di upload image qualsiasi fatta da android)

**Comment by nicholas0g** [comment]
Non è per nulla normale una risposta del genere. Hai provato ad utilizzare postman? Io si e funziona, e carica i file correttamente. Prova postman, vedrai che funzionerà e che quindi il problema dell'upload non è il server.
Certo che poi oltre all'eventuale problema che ha l'app android c'è da sistemare la risposta che restituisce il server in fase di errore. Aggiornerò scrivendo qui non appena avrò risolto questa cosa del messaggio d'errore. Per la funzionalità della chiamata invece una volta che verifico che su postman va per me è ottimale.

**Comment by Thecave3** [comment]
Mi serve comunque il log della chiamata per andare oltre.

**Comment by nicholas0g** [comment]
Non esiste il log della chiamata se l'unica cosa che ho ricevuto è la chiamata senza null'altro ...

**Comment by Thecave3** [comment]
Possibile che non c'è uan riga che dice cosa sta succedendo sul server? Sto inviando richieste e alternato mi mostra il messaggio di sopra e questo qui sotto. Non è possibile che non ti dica niente, cioè se ne accorge che qualcosa sta arrivando, deve dire per forza qualcosa.


` <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                                                                                   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
                                                                                <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
                                                                                <head>
                                                                                    <title>ERROR 502 - Bad Gateway!</title>
                                                                                    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                                                                                    <meta name="robots" content="noindex" />
                                                                                    <style type="text/css"></style>
                                                                                </head>
                                                                                <body>
                                                                                    <div id="page">
                                                                                        <div id="header" class="status5xx">
                                                                                            <h1>ERROR 502 - Bad Gateway!</h1>
                                                                                        </div>
                                                                                        <div id="content">
                                                                                            <h2>The following error occurred:</h2>
                                                                                            <p>This server received an invalid response from an upstream server it accessed to fulfill the request.</p>
                                                                                			<P>If you get this message repeatedly please contact the webmaster.</p>
                                                                                        </div>
                                                                                        <div id="footer">
                                                                                            <p>Powered by <a href="http://www.ispconfig.org">ISPConfig</a></p>
                                                                                        </div>
                                                                                    </div>
                                                                                </body>
                                                                                </html>`

**Comment by Thecave3** [comment]
Il problema del client lo sono riuscito a risolvere (o almen così sembra dalla risposta corretta che da il server). Permane però il problema che il server in caso di Unexpected field rimandi altre pagine web. Questa è una issue di cui solo il server si può occupare.

**Comment by nicholas0g** [comment]
Issue risolta: se viene inviato un file non valido o il campo file è vuoto il server ora risponde di conseguenza.
**ATTENZIONE:** le immagini caricate fino ad ora sono state cancellate dal filesystem!
